spring:
  datasource:
    url: jdbc:h2:mem:inventario_de_produtos
    username: Jumarket
    password: 1234
  jpa:
    hibernate:
      dll-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
